# Generated by Django 4.1.2 on 2022-11-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='url_pokemon',
            field=models.CharField(max_length=255),
        ),
    ]
